name: esim_compatibility
description: "Check if the device is eSIM compatible (native code for Android & iOS)."
version: 1.0.1
homepage: https://github.com/ejazrahim420
repository: https://github.com/ejazrahim420/esim_compatibility
issue_tracker: https://github.com/ejazrahim420/esim_compatibility/issues
license: MIT

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.codewithejaz.esim_compatibility
        pluginClass: EsimCompatibilityPlugin
      ios:
        pluginClass: EsimCompatibilityPlugin


